# Copyright 2025
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Fundación - Expedientes",
    "summary": "Gestión de expedientes con etapas, cuentas analíticas y relaciones con compras y proyectos",
    "version": "18.0.7.1",
    "category": "Administration",
    "website": "https://aceleradora.la",
    "author": "aceleradora.la",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "depends": [
        "mail",
        "hr",
        "purchase",
        "purchase_requisition",
        "project",
        "account",
    ],
    "assets": {
        "web.assets_backend": [
            "fund_expedient/static/src/js/document_file_viewer.js",
            "fund_expedient/static/src/xml/document_file_viewer.xml",
            "fund_expedient/static/src/scss/document_file_viewer.scss",
        ],
    },
    "data": [
        "security/fund_expedient_security.xml",
        "security/ir.model.access.csv",
        "data/legacy_cleanup.xml",
        "data/sequence_data.xml",
        "data/expedient_stage_data.xml",
        "data/expedient_encuadre_data.xml",
        "data/expedient_document_type_data.xml",
        "data/expedient_type_data.xml",
        "views/res_partner_views.xml",
        "views/expedient_document_type_views.xml",
        "views/fund_expedient_views.xml",
        "wizard/expedient_line_wizard_views.xml",
        "wizard/fund_expedient_notification_send_wizard_views.xml",
        "views/expedient_type_views.xml",
        "views/expedient_config_views.xml",
        "views/purchase_order_views.xml",
        "views/project_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/fund_budget_views.xml",
        "views/expedient_disposition_report_views.xml",
        "views/expedient_resolution_report_views.xml",
        "views/expedient_spend_request_views.xml",
        "views/expedient_locacion_report_views.xml",
        "reports/fund_expedient_spend_request_report.xml",
        "views/fund_expedient_menus.xml",
    ],
}
